{
    "affected_versions": [
        {
            "operator": "=",
            "version_value": "1.8"
        },
        {
            "operator": "=",
            "version_value": "1.8.1"
        },
        {
            "operator": "=",
            "version_value": "1.8.2"
        }
    ],
    "cve_id": "CVE-2015-5145",
    "cwe_id": "CWE-399",
    "description": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.",
    "impact": {
        "a": "HIGH",
        "ac": "LOW",
        "av": "NETWORK",
        "c": "NONE",
        "cvss2_score": 7.8,
        "cvss2_severity": "HIGH",
        "cvss3_score": 7.5,
        "cvss3_severity": "HIGH",
        "exploitability_score": 3.6,
        "i": "NONE",
        "impact_score": 3.9,
        "pr": "NONE",
        "s": "UNCHANGED",
        "ui": "NONE",
        "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "language": "python",
    "latest_version": "3.2.6",
    "license": "BSD-3-Clause",
    "name": "django",
    "ochrona_severity_score": 7.5,
    "owner": "Django Software Foundation",
    "publish_date": "2015-07-14T17:59Z",
    "references": [
        "https://www.djangoproject.com/weblog/2015/jul/08/security-releases/",
        "http://www.securityfocus.com/bid/75691",
        "https://security.gentoo.org/glsa/201510-06",
        "http://www.securitytracker.com/id/1032820"
    ],
    "repo_url": "https://github.com/django/django",
    "repository_summary": "A high-level Python Web framework that encourages rapid development and clean, pragmatic design."
}