{"name": "django", "cve_id": "CVE-2019-12781", "publish_date": "2019-07-01T14:15Z", "cwe_id": "CWE-20", "owner": "djangoproject", "affected_versions": [{"version_value": "1.11", "operator": "="}, {"version_value": "1.11.1", "operator": "="}, {"version_value": "1.11.2", "operator": "="}, {"version_value": "1.11.3", "operator": "="}, {"version_value": "1.11.4", "operator": "="}, {"version_value": "1.11.5", "operator": "="}, {"version_value": "1.11.6", "operator": "="}, {"version_value": "1.11.7", "operator": "="}, {"version_value": "1.11.8", "operator": "="}, {"version_value": "1.11.9", "operator": "="}, {"version_value": "1.11.10", "operator": "="}, {"version_value": "1.11.11", "operator": "="}, {"version_value": "1.11.12", "operator": "="}, {"version_value": "1.11.13", "operator": "="}, {"version_value": "1.11.14", "operator": "="}, {"version_value": "1.11.15", "operator": "="}, {"version_value": "1.11.16", "operator": "="}, {"version_value": "1.11.17", "operator": "="}, {"version_value": "1.11.18", "operator": "="}, {"version_value": "1.11.19", "operator": "="}, {"version_value": "1.11.20", "operator": "="}, {"version_value": "1.11.21", "operator": "="}, {"version_value": "2.1", "operator": "="}, {"version_value": "2.1.1", "operator": "="}, {"version_value": "2.1.2", "operator": "="}, {"version_value": "2.1.3", "operator": "="}, {"version_value": "2.1.4", "operator": "="}, {"version_value": "2.1.5", "operator": "="}, {"version_value": "2.1.6", "operator": "="}, {"version_value": "2.1.7", "operator": "="}, {"version_value": "2.1.8", "operator": "="}, {"version_value": "2.1.9", "operator": "="}, {"version_value": "2.2", "operator": "="}, {"version_value": "2.2.1", "operator": "="}, {"version_value": "2.2.2", "operator": "="}], "references": ["http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html", "http://www.openwall.com/lists/oss-security/2019/07/01/3", "http://www.securityfocus.com/bid/109018", "https://docs.djangoproject.com/en/dev/releases/security/", "https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL/", "https://seclists.org/bugtraq/2019/Jul/10", "https://security.netapp.com/advisory/ntap-20190705-0002/", "https://usn.ubuntu.com/4043-1/", "https://www.debian.org/security/2019/dsa-4476", "https://www.djangoproject.com/weblog/2019/jul/01/security-releases/"], "description": "An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP.", "latest_version": "2.2.6", "language": "python", "license": "BSD-3-Clause", "repository_summary": "A high-level Python Web framework that encourages rapid development and clean, pragmatic design.", "repo_url": "https://github.com/django/django", "impact": {"cvss2_score": 5.0, "cvss2_severity": "MEDIUM", "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "av": "NETWORK", "ac": "LOW", "pr": "NONE", "c": "LOW", "i": "NONE", "a": "NONE", "impact_score": 1.4, "exploitability_score": 3.9, "cvss3_score": 5.3, "cvss3_severity": "MEDIUM", "ui": "NONE", "s": "UNCHANGED"}, "ochrona_severity_score": 5.3}