{"name": "django", "cve_id": "CVE-2020-13254", "publish_date": "2020-06-03T14:15Z", "cwe_id": "CWE-295", "owner": "Django Software Foundation", "affected_versions": [{"version_value": "2.2a1", "operator": "="}, {"version_value": "2.2b1", "operator": "="}, {"version_value": "2.2rc1", "operator": "="}, {"version_value": "2.2", "operator": "="}, {"version_value": "2.2.1", "operator": "="}, {"version_value": "2.2.2", "operator": "="}, {"version_value": "2.2.3", "operator": "="}, {"version_value": "2.2.4", "operator": "="}, {"version_value": "2.2.5", "operator": "="}, {"version_value": "2.2.6", "operator": "="}, {"version_value": "2.2.7", "operator": "="}, {"version_value": "2.2.8", "operator": "="}, {"version_value": "2.2.9", "operator": "="}, {"version_value": "2.2.10", "operator": "="}, {"version_value": "2.2.11", "operator": "="}, {"version_value": "2.2.12", "operator": "="}, {"version_value": "3.0a1", "operator": "="}, {"version_value": "3.0b1", "operator": "="}, {"version_value": "3.0rc1", "operator": "="}, {"version_value": "3.0", "operator": "="}, {"version_value": "3.0.1", "operator": "="}, {"version_value": "3.0.2", "operator": "="}, {"version_value": "3.0.3", "operator": "="}, {"version_value": "3.0.4", "operator": "="}, {"version_value": "3.0.5", "operator": "="}, {"version_value": "3.0.6", "operator": "="}], "references": ["https://usn.ubuntu.com/4381-2/", "https://github.com/advisories/GHSA-wpjr-j57x-wxfw", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/", "https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ", "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/", "https://security.netapp.com/advisory/ntap-20200611-0002/", "https://www.debian.org/security/2020/dsa-4705", "https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html", "https://docs.djangoproject.com/en/3.0/releases/security/", "https://nvd.nist.gov/vuln/detail/CVE-2020-13254", "https://usn.ubuntu.com/4381-1/"], "description": "From NVD:\nAn issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage.\nFrom Github:\nAn issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage.", "latest_version": "3.1.3", "language": "python", "license": "BSD-3-Clause", "repository_summary": "A high-level Python Web framework that encourages rapid development and clean, pragmatic design.", "repo_url": "https://www.djangoproject.com/", "impact": {"cvss2_score": 4.3, "cvss2_severity": "MEDIUM", "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N", "av": "NETWORK", "ac": "HIGH", "pr": "NONE", "c": "HIGH", "i": "NONE", "a": "NONE", "impact_score": 3.6, "exploitability_score": 2.2, "cvss3_score": 5.9, "cvss3_severity": "MEDIUM", "ui": "NONE", "s": "UNCHANGED"}, "ochrona_severity_score": 5.9}