{
    "name": "opencv-contrib-python",
    "cve_id": "CVE-2016-1516",
    "publish_date": "2017-04-10T03:59Z",
    "cwe_id": "CWE-415",
    "owner": "Olli-Pekka Heinisuo",
    "affected_versions": [
        {
            "version_value": "3.3.0.10",
            "operator": "<="
        }
    ],
    "references": [
        "https://github.com/opencv/opencv/issues/5956",
        "https://nvd.nist.gov/vuln/detail/CVE-2016-1516",
        "https://arxiv.org/pdf/1701.04739.pdf",
        "https://github.com/advisories/GHSA-cvhw-2593-5j2q",
        "https://lists.debian.org/debian-lts-announce/2018/07/msg00030.html"
    ],
    "description": "From NVD:\nOpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code.\nFrom Github:\nOpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV 3.3.1.11).",
    "latest_version": "4.5.3.56",
    "language": "python",
    "license": "MIT",
    "repository_summary": "Wrapper package for OpenCV python bindings.",
    "repo_url": "https://github.com/skvark/opencv-python",
    "impact": {
        "cvss2_score": 6.8,
        "cvss2_severity": "MEDIUM",
        "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
        "av": "NETWORK",
        "ac": "LOW",
        "pr": "NONE",
        "c": "HIGH",
        "i": "HIGH",
        "a": "HIGH",
        "impact_score": 5.9,
        "exploitability_score": 2.8,
        "cvss3_score": 8.8,
        "cvss3_severity": "HIGH",
        "ui": "REQUIRED",
        "s": "UNCHANGED"
    },
    "ochrona_severity_score": 8.8
}