{"name": "python3-dateutil", "cve_id": null, "publish_date": "2019-12-01T00:00Z", "cwe_id": "CAPEC-630", "owner": "olgired2017", "affected_versions": [{"version_value": "-", "operator": "="}], "references": ["https://pypi.org/project/python3-dateutil/", "https://github.com/dateutil/dateutil/issues/984", "https://www.zdnet.com/article/two-malicious-python-libraries-removed-from-pypi/"], "description": "python3-dateutil package doesn't contain malicious code of its own, however it included the malicious 'jeIlyfish' imposter package which included an encoded python file that will attempt to exfiltrate any SSH or GPG keys found on the host machine to a remote server.", "latest_version": null, "language": "python", "license": "Not Applicable", "repository_summary": null, "repo_url": null, "impact": {"cvss2_score": null, "cvss2_severity": null, "vector_string": null, "av": null, "ac": null, "pr": null, "c": null, "i": null, "a": null, "impact_score": null, "exploitability_score": null, "cvss3_score": null, "cvss3_severity": null, "ui": null, "s": null}, "ochrona_severity_score": 8.0}