{"impact": {"pr": null, "a": "COMPLETE", "ac": "LOW", "impact_score": null, "i": "COMPLETE", "cvss3_score": null, "c": "COMPLETE", "vector_string": "AV:N/AC:M/Au:S/C:P/I:P/A:P", "cvss2_severity": "MEDIUM", "cvss3_severity": null, "s": null, "ui": null, "av": "LOCAL", "cvss2_score": 6.0, "au": "SINGLE", "exploitability_score": null}, "license": "Apache-2.0", "name": "python-keystoneclient", "cve_id": "CVE-2014-0105", "repository_summary": "Client Library for OpenStack Identity", "ochrona_severity_score": 6.0, "repo_url": "https://github.com/openstack/python-keystoneclient", "latest_version": "3.22.0", "cwe_id": "CWE-255", "language": "python", "publish_date": "2014-04-15T14:55Z", "references": ["http://rhn.redhat.com/errata/RHSA-2014-0382.html", "http://rhn.redhat.com/errata/RHSA-2014-0409.html", "http://www.openwall.com/lists/oss-security/2014/03/27/4", "https://bugs.launchpad.net/python-keystoneclient/+bug/1282865"], "owner": "openstack", "affected_versions": [{"operator": "<=", "version_value": "0.7.0"}], "description": "The auth_token middleware in the OpenStack Python client library for Keystone (aka python-keystoneclient) before 0.7.0 does not properly retrieve user tokens from memcache, which allows remote authenticated users to gain privileges in opportunistic circumstances via a large number of requests, related to an \"interaction between eventlet and python-memcached.\""}