{"name": "scapy", "cve_id": "CVE-2019-1010142", "publish_date": "2019-07-19T16:15Z", "cwe_id": "CWE-400", "owner": "scapy", "affected_versions": [{"version_value": "2.4.0", "operator": "<="}], "references": ["http://www.securityfocus.com/bid/106674", "https://github.com/secdev/scapy/pull/1409", "https://github.com/secdev/scapy/pull/1409/files#diff-441eff981e466959968111fc6314fe93L1058", "https://www.imperva.com/blog/scapy-sploit-python-network-tool-is-vulnerable-to-denial-of-service-dos-attack-cve-pending/"], "description": "scapy 2.4.0 is affected by: Denial of Service. The impact is: infinite loop, resource consumption and program unresponsive. The component is: _RADIUSAttrPacketListField.getfield(self..). The attack vector is: over the network or in a pcap. both work.", "latest_version": "2.4.3", "language": "python", "license": "GPL-2.0-only", "repository_summary": "Scapy: interactive packet manipulation tool", "repo_url": "https://github.com/secdev/scapy", "impact": {"cvss2_score": 5.0, "cvss2_severity": "MEDIUM", "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "av": "NETWORK", "ac": "LOW", "pr": "NONE", "c": "NONE", "i": "NONE", "a": "HIGH", "impact_score": 3.6, "exploitability_score": 3.9, "cvss3_score": 7.5, "cvss3_severity": "HIGH", "ui": "NONE", "s": "UNCHANGED"}, "ochrona_severity_score": 7.5}