{"impact": {"pr": null, "a": "COMPLETE", "ac": "LOW", "impact_score": null, "i": "COMPLETE", "cvss3_score": null, "c": "COMPLETE", "vector_string": "AV:N/AC:M/Au:S/C:P/I:P/A:P", "cvss2_severity": "MEDIUM", "cvss3_severity": null, "s": null, "ui": null, "av": "LOCAL", "cvss2_score": 6.0, "au": "SINGLE", "exploitability_score": null}, "license": "ZPL-2.1", "name": "zodb", "cve_id": "CVE-2009-2701", "repository_summary": "ZODB, a Python object-oriented database", "ochrona_severity_score": 6.0, "repo_url": "https://github.com/zopefoundation/zodb", "latest_version": "5.5.1", "cwe_id": "NVD-CWE-noinfo", "language": "python", "publish_date": "2009-09-08T18:30Z", "references": ["http://pypi.python.org/pypi/ZODB3/3.8.3", "http://pypi.python.org/pypi/ZODB3/3.9.0c2", "http://www.vupen.com/english/advisories/2009/2534", "https://mail.zope.org/pipermail/zope-announce/2009-September/002221.html"], "owner": "zope", "affected_versions": [{"operator": "=", "version_value": "3.8"}, {"operator": "=", "version_value": "3.8.0"}, {"operator": "=", "version_value": "3.8.1"}, {"operator": "=", "version_value": "3.8.2"}, {"operator": "=", "version_value": "3.9.0"}, {"operator": "=", "version_value": "3.9.0b1"}, {"operator": "=", "version_value": "3.9.0b2"}, {"operator": "=", "version_value": "3.9.0b3"}, {"operator": "=", "version_value": "3.9.0b4"}, {"operator": "=", "version_value": "3.9.0b5"}, {"operator": "=", "version_value": "3.9.0c1"}], "description": "Unspecified vulnerability in the Zope Enterprise Objects (ZEO) storage-server functionality in Zope Object Database (ZODB) 3.8 before 3.8.3 and 3.9.x before 3.9.0c2, when certain ZEO database sharing and blob support are enabled, allows remote authenticated users to read or delete arbitrary files via unknown vectors."}